services:
  cassandra:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    command:
        - /bin/sh
        - -c
        - redis-server --requirepass "$${PASSWORD_REDIS:?PASSWORD_REDIS variable is not set}"
    volumes:
       - /mnt/docker/volumes/redis:/data
    env_file: ../../../../cmd/.env  

    
       
       

