version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    container_name: cassandra
    volumes:
       - /mnt/docker/volumes/cassandra:/var/lib/cassandra
       
       

